name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 * * *"

jobs:

  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
